### ISSUE TITLE
Am not able to view the add-on menus and interface elements -- see only some wallpaper

### ISSUE THREAD

**Issue by TDunnavant** [Colossal1/plugin.video.youporn#1]
I'm a user of Kodi 17.4.  When I select the Youporn 3.000.000 addon to use, all I see are some wallpaper images that cycle at about a 5-second interval.  There are some action buttons at the top of the screen -- Exit, Previous, Next, and Search.  The only one that "works" is "Exit".  If I select that one, the add-on shuts down.

**Comment by morbiusprime** [comment]
Same issue

**Comment by Ichijoe2112** [comment]
And, even that won't work on my nVIDIA Shield TV. I have to force quit Kodi to get out of it. This happend with Kodi 17.3 as well. But being on 17.4, I thought it was time to see if any updates were made. Apperenty there have been according to the logs. However the Add-on still doesn't work.

**Comment by Colossal1** [comment]
This is the first time I have ever heard of this issue.

For me to be able to offer any glimps into the issue I will need to see some logs from some of you. 

Thanks

**Comment by Colossal1** [comment]
Never mind with the log, I get the same issue here so I will look tonight and try to fix it. Thanks for letting me know.

**Comment by Colossal1** [comment]
Fixed in 3.00.001
