### ISSUE TITLE
No Icons

### ISSUE THREAD

**Issue by Levi232** [Colossal1/plugin.video.youporn#3]
Hello, first of all, thank you for the addon. The problem i have, is that the icons of the videos don't appear.

Have a good day.

**Comment by allanbech** [comment]
I can confirm, I have the same issue here since the lastest update.
There's is no "preview of the video" just blank icon with text.
Everything else works fine.

Again thanks for your contribution to make this addon.

**Comment by WexVoper** [comment]
I have the same issue.

**Comment by Colossal1** [comment]
I will look into it today.

**Comment by Colossal1** [comment]
Fixed ready for next update.
